[init]
Async-Swift/AsyncSwift pull request #22
Opened 2022-09-12 13:35 UTC by insub4067

2022-09-12 13:52 UTC, unnnyong commented
```diff
diff --git a/AsyncSwift/Observed/EventDetailView+Observed.swift b/AsyncSwift/Observed/EventDetailView+Observed.swift
index cf01070..a91b44c 100644
--- a/AsyncSwift/Observed/EventDetailView+Observed.swift
+++ b/AsyncSwift/Observed/EventDetailView+Observed.swift
@@ -11,7 +11,11 @@ import EventKit
 extension EventDetailView {
     final class Observed: ObservableObject {

-        @Published var event = Event()
+        init(event: Event) {
+            self.event = event
+        }
+
+        @Published var event: Event
         @Published var isShowingSheet = false
         @Published var isShowingAddEventConfirmationAlert = false
         @Published var isShowingAddEventSuccessAlert = false
diff --git a/AsyncSwift/Views/EventDetailView.swift b/AsyncSwift/Views/EventDetailView.swift
index 4cb63d1..3bc215d 100644
--- a/AsyncSwift/Views/EventDetailView.swift
+++ b/AsyncSwift/Views/EventDetailView.swift
@@ -9,10 +9,10 @@ import SwiftUI

 struct EventDetailView: View {

-    @StateObject var observed = Observed()
+    @ObservedObject var observed: Observed

     init(event: Event) {
-//        self.observed.event = event
+        self.observed = Observed(event: event)
     }

     var body: some View {
```

2022-09-13 08:38 UTC, unnnyong commented on AsyncSwift/Models/JSONResponse.swift
> +//  EventResponse.swift
struct이 갖고있는 property들이 let 이 아닌 var 로 정의하신 이유가 있으실까요 ?

2022-09-14 00:35 UTC, unnnyong commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
```suggestion
struct GetEventResponse: Codable {
```

모든 JSONResponse를 담는 것이 아니라, 
Event 를 get 할 때의 Response model의 구조만 갖고있는 것 같아서 분리하면 좋을 것 같습니다.

2022-09-14 00:36 UTC, unnnyong commented on AsyncSwift/Models/JSONResponse.swift
> +    var sessions: [Session]
```suggestion
    var event = Event()
    var sessions: [Session] = []
```
property에 값이 init에서 무조건 주입된다면, init method가 없어도 되지 않을까 싶네요.. !

2022-09-14 00:37 UTC, unnnyong commented on AsyncSwift/Observed/EventDetailView+Observed.swift
>  import Foundation
```suggestion
```

SwiftUI가 추가되어서 삭제될 수 있네요 ✨

2022-09-14 00:37 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
>  import Foundation
```suggestion
```

SwiftUI가 추가되어서 삭제될 수 있네요 ✨

2022-09-14 01:01 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +            dataTask.resume()
- JSON Response가 Parsing이 끝난 이후에도 Model로 값을 계속 가지고있어야할까요 ? 
    Parsing이 마무리된 이후에는 View에서 필요한 값만 Observed가 갖고있는게 맞지않을까 싶네요 .. !
- 더불어서 fetch method에서 guard let 을 한 곳에서 사용하는 수정으로 인덴트를 줄여보았습니다 보시고 코멘트 부탁드려요

```suggestion
        @Published var event = Event()
        @Published var sessions: [Session] = []

        @Published var eventStatus: EventStatus = .upcoming

        init() {
            fetchJson()
        }

    private extension Observed {
        func fetchJson() {
            guard let url = URL(string: "https://async-swift.github.io/jsonstorage/asyncswift.json") else { return }
            let request = URLRequest(url: url)
            let dataTask = URLSession.shared.dataTask(with: request) { data, response, _ in

                guard
                    let response = response as? HTTPURLResponse,
                    response.statusCode == 200,
                    let data = data
                else { return }

                DispatchQueue.main.async { [weak self] in
                    guard let self = self else { return }

                    do {
                        let decodedData = try JSONDecoder().decode(JSONResponse.self, from: data)
                        withAnimation {
                            self.event = decodedData.event
                            self.sessions = decodedData.sessions
                        }
                        self.calculateEventStatus()

                    } catch let error {
                        print("❌ \(error.localizedDescription)")
                    }
                }
            }
            dataTask.resume()
```

2022-09-14 01:03 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +            if let start = start, let end = end {
```suggestion
            guard
                let start = formatter.date(from: event.startDate),
                let end = formatter.date(from: event.endDate)
            else { return }

            let current = Date()
```

guard let을 사용한다면 property 정의와 Optional 확인을 한 번에 할 수 있습니다

2022-09-14 01:05 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +                VStack(alignment: .leading, spacing: 8) {
```suggestion
                VStack(alignment: .leading) {
```

8이 default value였던 것 같아서 생략 가능할까요 ?

2022-09-14 01:07 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +                    }
이 두개의 scope내 핸들링이 같아보이는데 괜찮은건가요 .. ??? 👀

2022-09-14 01:50 UTC, insub4067 commented on AsyncSwift/Observed/EventDetailView+Observed.swift
>  import Foundation
확인했습니다 수정하도록 하겠습니다

2022-09-14 01:50 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
>  import Foundation
확인했습니다 수정하도록 하겠습니다

2022-09-14 01:54 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +    var sessions: [Session]
확인했습니다 수정하도록 하겠습니다

2022-09-14 01:54 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
확인했습니다 수정하겠습니다

2022-09-14 02:05 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +//  EventResponse.swift
Published 이기 때문에 최초에 init 될때에 값을 가지고 있는 property가 있고,
후에 fetchJson 이 실행되고 가지고온 값을 Published로 선언된 변수에 재할당 하게 됩니다

2022-09-14 02:05 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +struct Session: Codable, Identifiable {
확인했습니다 수정하도록 하겠습니다

2022-09-14 02:16 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
> +            dataTask.resume()
최고의 리뷰어 이십니다 크 

두개의 @Published 로 event 와 sessions 를 나누길 원하시는건가요?

위에 코맨트 남겨 주신거 보면 Event안에 property로 sessions 를 넣자고 하셨는데

위 코맨트를 적용하고 남겨주신 코드까지 적용하게 된다면,

@Property var event 안에 sessions로 값이 할당 되어있고,

@Property var sessions 로 다시 한번 존재하게 됩니다

2022-09-14 02:16 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
> +            if let start = start, let end = end {
맞네요 바로 수정하겠습니다

2022-09-14 02:36 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +            dataTask.resume()
> 위에 코맨트 남겨 주신거 보면 Event안에 property로 sessions 를 넣자고 하셨는데

네 작성드린 코드는 현재 구조를 유지한 채로 작성드렸습니다.

2022-09-14 03:16 UTC, insub4067 commented on AsyncSwift/Views/SessionView.swift
> +                    }
https://developer.apple.com/documentation/swiftui/asyncimage

에러가 발생했을 경우와 로딩되는동안 place holder 역할을 하는 경우에 대한 처리입니다
애플에서 정식으로 지원하고 있는 코드 구조입니다 위 링크에서 확인 가능하십니다

2022-09-14 03:32 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +            dataTask.resume()
> 위에 코맨트 남겨 주신거 보면 Event안에 property로 sessions 를 넣자고 하셨는데
위 코맨트를 적용하고 남겨주신 코드까지 적용하게 된다면,

아직 위의 코멘트를 적용하시지 않은 상태여서 현재 구조를 유지한채로 리뷰를 진행한 상태입니다.
위의 코멘트를 적용하신다면 Event 만 존재해도 된다고 생각해요.

이 리뷰 코멘트의 요지는 Observed에서 Response Model을 가지고 있는 것에 대한 것이였습니다.

2022-09-14 03:36 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
> +            dataTask.resume()
그러면 현재 남겨주신 코드에서 @Property var sessions는 없이 event의 접근자로 view에 data 전달하는 구조로 수정해서 커밋 올리도록 하겠습니다

2022-09-14 05:41 UTC, song-cool commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
동사 원형으로 시작하는 네이밍은 함수랑 착각하게 만들 수 있을것같아요! 우디 어찌생각하나요?

2022-09-14 06:40 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
아니면 어차피 지금 Event 안에 sessions가 들었으니까 json을 수정해서 바로 event struct에 맞게 수정하는거 어떨까요?

2022-09-14 06:40 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
추후에 TicketingView 혹은 StampView 에서 필요한 내용들 지금 이 json에 모두 담으실껀가요?

2022-09-14 07:06 UTC, unnnyong commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
> 추후에 TicketingView 혹은 StampView 에서 필요한 내용들 지금 이 json에 모두 담으실껀가요?

별도로 생각하고 있었어요 ~ !

2022-09-14 10:40 UTC, unnnyong requested changes
🙏

2022-09-14 10:40 UTC, unnnyong commented on AsyncSwift/AppDelegate.swift
> -    static var orientationLock = UIInterfaceOrientationMask.all
🤩🤩

2022-09-14 10:40 UTC, unnnyong commented on AsyncSwift/Models/EventModel.swift
> +        case description = "description"
이 케이스만 별도로 적혀진 이유가 있나요 ?

2022-09-14 10:40 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
>  import Foundation
👀

2022-09-14 10:40 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +            let current = Date()
currentDate 로 하면 어떨지 제안드립니다

2022-09-14 10:40 UTC, unnnyong commented on AsyncSwift/Views/EventView.swift
>   1. light mode only
요 부분들은 언제 해결이 될까요 ??

2022-09-14 10:51 UTC, insub4067 commented on AsyncSwift/Views/EventView.swift
>   1. light mode only
아 이거 이미 적용했어요...!! 
지우겠습니다

2022-09-14 13:28 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
> +            let current = Date()
좋은 아이디어 입니다 수정하겠습니다

2022-09-14 13:29 UTC, insub4067 commented on AsyncSwift/AppDelegate.swift
> -    static var orientationLock = UIInterfaceOrientationMask.all
호호호

2022-09-14 13:30 UTC, insub4067 commented on AsyncSwift/Models/EventModel.swift
> +        case description = "description"
그건 json 파씽을 위해 Codable을 상속받기 위해 이렇게 하라고 애플에서 이야기해주고 있기 때문입니다 하하

2022-09-14 13:30 UTC, insub4067 commented on AsyncSwift/Observed/EventView+Observed.swift
>  import Foundation
어우 이게 왜 ..

2022-09-14 13:32 UTC, insub4067 commented on AsyncSwift/Models/JSONResponse.swift
> +struct JSONResponse: Codable {
좋습니다

2022-09-14 16:09 UTC, unnnyong commented on AsyncSwift/Models/EventModel.swift
> +        case description = "description"
아하

2022-09-14 17:04 UTC, unnnyong commented on AsyncSwift/Models/EventModel.swift
> +struct Event: Codable {
IMO로 get만 할 때는 Decodable도 되지 않을까 싶네요

2022-09-14 17:04 UTC, unnnyong commented on AsyncSwift/Observed/EventView+Observed.swift
> +                       withAnimation {
이게 트리거로 멋진 애니메이션이 나오는거였군요 👾

2022-09-14 17:05 UTC, unnnyong approved these changes
お疲れ様でした！ 🍵 🍵 🍵 🍵

2022-09-14 17:14 UTC, merged