[Feat] EventView 1차 완성
Async-Swift/AsyncSwift pull request #7
Opened 2022-09-08 13:15 UTC by insub4067

2022-09-08 13:16 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +//}
```suggestion
```

2022-09-08 13:16 UTC, unnnyong commented on AsyncSwift/Views/EventView.swift
> + */
이건 TODO 인가요 .. ???? 👀

2022-09-08 13:17 UTC, unnnyong commented on AsyncSwift/Views/EventView.swift
> +struct EventModel {
그냥 Event로 해도되지않을까요 ??

2022-09-08 13:17 UTC, insub4067 commented on AsyncSwift/Views/EventView.swift
> + */
넹

2022-09-08 13:20 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +    let data = EventModel.mockData
```suggestion
    private let data = EventModel.mockData
```

2022-09-08 13:21 UTC, unnnyong commented on AsyncSwift/Views/EventView.swift
> + */
// TODO 표시 해주세요 ~~~ !!

2022-09-08 13:23 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +    let data: EventModel.Session
```suggestion
    private let data: EventModel.Session
```

2022-09-08 13:25 UTC, song-cool commented on AsyncSwift/Views/EventDetailView.swift
> +                            .font(.system(size: 17))
font size를 시스템 폰트크기설정한 유저를 고려하여 폰트 이름을 직접 사용해주세요!
```suggestion
                            .font(.body))
```

2022-09-08 13:26 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +        .navigationTitle("Session")
enum 에 property를 추가해서 가져오면 어떤가요 ? 
새로 Tab이 추가되거나 기존 Tab이 수정되었을 때 유지보수에 좋을 거 같습니다 ~

2022-09-08 13:34 UTC, song-cool commented on AsyncSwift/Views/EventDetailView.swift
> +                            .fixedSize(horizontal: false, vertical: true)
이것은 개행을 위한 코드인가요?

2022-09-08 14:12 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +    let data: EventModel.Event
init method의 parameter 이름과 통일하면어떨까요 ? 👀

2022-09-08 14:23 UTC, song-cool commented on AsyncSwift/Views/EventDetailView.swift
> +
개행의 기준이 궁금합니다!

2022-09-08 15:14 UTC, unnnyong commented on AsyncSwift.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 76AJ433CP5;
😢 😢 😢

2022-09-08 15:17 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                    .font(.system(size: 17))
https://github.com/Async-Swift/AsyncSwift/pull/7/files#r966100757

2022-09-08 15:18 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +
action 들은 어디갔...나요 ... ???? 😢 
아직 정의되지 않았다면 TODO로 정의가 필요할듯합니다 !

2022-09-08 15:31 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +//}
```suggestion
```

2022-09-08 15:33 UTC, unnnyong commented on AsyncSwift/Views/EventView.swift
> +//}
```suggestion
```

2022-09-08 15:33 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +        .navigationTitle("Session")
enum에서 property로 가져서 return하도록하면 어떨까요 ??

2022-09-08 15:33 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +                .font(.system(size: 20))
👀

2022-09-08 15:34 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +                    .font(.system(size: 17))
👀

2022-09-08 15:34 UTC, unnnyong commented on AsyncSwift/Views/SessionView.swift
> +                    .font(.system(size: 11))
👀

2022-09-08 16:40 UTC, E-know commented on AsyncSwift/Views/EventDetailView.swift
> +
TODO 주석을 

`// TODO: 내용` 

으로 수정해주세요.

2022-09-08 16:41 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                .fontWeight(.bold)
title3에 bold가 포함되어있지 않을까요 .. ??? 👀

2022-09-08 16:41 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                .fontWeight(.bold)
title 3가 regular이므로 설정 필요함. from. @E-know

2022-09-08 16:42 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                .font(.system(size: 20))
```suggestion
```

위에서 title 3가 20이라면 삭제가 필요할듯해요 !

2022-09-08 16:42 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                    .font(.system(size: 20))
```suggestion
```

2022-09-08 16:43 UTC, song-cool requested changes
수정 요청합니다! 고생하셨어요 :)

2022-09-09 05:49 UTC, unnnyong commented
Conflict가 발생했어요 .. ! 😢

2022-09-09 05:50 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +    }
생락 가능해보여요 ~ 👀  ..!

2022-09-09 05:52 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +                information
복잡한 Stack들의 View가 property로 빠지니 body가 무척이나 깔끔해졌네요 ~ ✨

2022-09-09 05:52 UTC, unnnyong commented on AsyncSwift/Views/EventDetailView.swift
> +
```suggestion
// TODO: Add action 
```

2022-09-09 05:58 UTC, E-know commented on AsyncSwift/Views/EventView.swift
> +//            .navigationTitle("Event")
주석의 역할이 궁금합니다!

2022-09-09 06:00 UTC, E-know commented on AsyncSwift/Views/EventView.swift
> +                    .font(.footnote)
footnote에 이미 fontweight가 regular가 설정되어 있어서 중복 설정하게 되는것 같습니다 수정이 필요합니다.

2022-09-09 06:43 UTC, closed without merging